Repository loteque/wasteland-warrior, pull requests merged in 2023-02, with the labels that each got.

#57 changed directory of terrain tiles
  project/.import/bottlecap.png-1e9237ec09e366ffcf65204162294a80.md5
  project/.import/bottlecap.png-1e9237ec09e366ffcf65204162294a80.stex
  project/.import/snapper_walk.png-d499ae1c4df0ee075e0de4add7c20219.md5
  project/.import/snapper_walk.png-d499ae1c4df0ee075e0de4add7c20219.stex
  project/.import/terrain_01.png-9fe3fae1c1dc83703562ea615b9ce56b.md5
  project/.import/terrain_01.png-9fe3fae1c1dc83703562ea615b9ce56b.stex
  project/.import/terrain_02.png-33c134adefbcdd84593ec02ab36a2fcc.md5
  project/.import/terrain_02.png-33c134adefbcdd84593ec02ab36a2fcc.stex
  project/.import/terrain_03.png-e3a0e4384a906ad79c8b90a1742e7303.md5
  project/.import/terrain_03.png-e3a0e4384a906ad79c8b90a1742e7303.stex
  project/.import/terrain_04.png-e1dde2d77964e0f43a739fb4a4fadad3.md5
  project/.import/terrain_04.png-e1dde2d77964e0f43a739fb4a4fadad3.stex
  project/.import/terrain_05.png-760ee37472152d58f11ea0d9f633eaf0.md5
  project/.import/terrain_05.png-760ee37472152d58f11ea0d9f633eaf0.stex
  project/.import/terrain_06.png-c278eb76f6a61db0df5c760743051b5a.md5
  project/.import/terrain_06.png-c278eb76f6a61db0df5c760743051b5a.stex
  project/.import/terrain_07.png-f9238cbbdd717fb71a4f0c8559fbce69.md5
  project/.import/terrain_07.png-f9238cbbdd717fb71a4f0c8559fbce69.stex
  project/.import/terrain_08.png-bd5855fca5ffa0025820640dccd7b7be.md5
  project/.import/terrain_08.png-bd5855fca5ffa0025820640dccd7b7be.stex
  project/.import/terrain_09.png-d96ff298fbd7241aecdbf394301c89dc.md5
  project/.import/terrain_09.png-d96ff298fbd7241aecdbf394301c89dc.stex
  project/.import/terrain_10.png-bec5813bf5deb4693b2bb3a40778b235.md5
  project/.import/terrain_10.png-bec5813bf5deb4693b2bb3a40778b235.stex
  project/.import/terrain_11.png-cf1084bcdb5afb36e7bea909939795f3.md5
  project/.import/terrain_11.png-cf1084bcdb5afb36e7bea909939795f3.stex
  project/.import/terrain_12.png-b0c10dbbafbb0b5df5416900dcaae405.md5
  project/.import/terrain_12.png-b0c10dbbafbb0b5df5416900dcaae405.stex
  project/assets/char/snapper_walk.png.import
  project/assets/char/sprite_cheatsheet.txt
  project/assets/env/terrain_01.png
  project/assets/env/terrain_01.png.import
  project/assets/env/terrain_02.png
  project/assets/env/terrain_02.png.import
  project/assets/env/terrain_03.png
  project/assets/env/terrain_03.png.import
  project/assets/env/terrain_04.png
  project/assets/env/terrain_04.png.import
  project/assets/env/terrain_05.png
  project/assets/env/terrain_05.png.import
  project/assets/env/terrain_06.png
  project/assets/env/terrain_06.png.import
  project/assets/env/terrain_07.png
  project/assets/env/terrain_07.png.import
  project/assets/env/terrain_08.png
  project/assets/env/terrain_08.png.import
  project/assets/env/terrain_09.png
  project/assets/env/terrain_09.png.import
  project/assets/env/terrain_10.png
  project/assets/env/terrain_10.png.import
  project/assets/env/terrain_11.png
  project/assets/env/terrain_11.png.import
  project/assets/env/terrain_12.png
  project/assets/env/terrain_12.png.import
  project/assets/pickup/bottlecap.png
  project/assets/pickup/bottlecap.png.import
  project/project.godot
  project/src/BackgroundChunk.tscn
  project/src/CameraController.gd
Labels: environment, art

#60 fix procedural generation
  project/src/BackgroundGenerator.gd
Labels: environment, programming

#62 add player sprites
  project/assets/char/player_idle.png
  project/assets/char/player_run.png
  project/assets/char/snapper_walk.png
  project/assets/char/sprite_cheatsheet.txt
  project/assets/pickup/bottlecap.png
Labels: character, art, animation

#68 add projectile sprite
  project/assets/char/projectile.png
  project/assets/char/sprite_cheatsheet.txt
Labels: character, art

#70 Flash player when they get hit by mob
  project/src/PlayerController.gd
  project/src/PlayerController.tscn
Labels: art, animation, programming, shader

#72 Adds player projectiles and enemy damage and death
  project/.import/projectile.png-b15f4695d3ad9833a3e3d66ec84f8dff.md5
  project/.import/projectile.png-b15f4695d3ad9833a3e3d66ec84f8dff.stex
  project/assets/char/projectile.png.import
  project/src/PlayerController.gd
  project/src/PlayerController.tscn
  project/src/Projectile.gd
  project/src/Projectile.tscn
  project/src/mobs/Mob.gd
  project/src/mobs/Mob.tscn
  project/test/TestPlayerHurt.tscn
  project/test/TestPlayerHurtEnemy.tscn
  project/test/TestProjectile.tscn
Labels: character, programming

#75 add player run animation sprite
  project/src/PlayerController.gd
  project/src/PlayerController.tscn
Labels: animation, programming

#79 Makes Snapper and player flash on hit
  project/src/PlayerController.tscn
  project/src/mobs/Mob.gd
  project/src/mobs/Mob.tscn
  project/src/mobs/hit_flash_red.gdshader
  project/src/mobs/hit_flash_white.gdshader
  project/test/TestPlayerHurt.tscn
  project/test/TestPlayerHurtEnemy.tscn
Labels: character, animation, programming, shader

#81 Make mobs drop caps when killed, allow pickup
  project/src/PlayerController.gd
  project/src/PlayerController.tscn
  project/src/mobs/Mob.gd
  project/src/pickups/BottleCap.gd
  project/src/pickups/BottleCap.tscn
  project/test/PlayerSimulator.gd
  project/test/PlayerSimulator.tscn
  project/test/TestMobsDropCaps.tscn
  project/test/TestPickupCaps.tscn
Labels: character, animation, programming, pickup

#85 add xp bar and single player sprite sheet
  project/assets/char/player_anims.png
  project/assets/char/sprite_cheatsheet.txt
  project/assets/ui/xp_bar.png
  project/assets/ui/xp_bar_endcap.png
  project/assets/ui/xp_bubbles.png
Labels: art

#86 add player idle animation sprite
  project/src/PlayerController.gd
  project/src/PlayerController.tscn
Labels: animation, programming

#90 add 9 sliced xp bar
  project/.import/xp_bar_9slice.png-4263660116b649f5b4fb9a60b3125610.md5
  project/.import/xp_bar_9slice.png-4263660116b649f5b4fb9a60b3125610.stex
  project/assets/sprite_cheatsheet.txt
  project/assets/ui/xp_bar_9slice.png
  project/assets/ui/xp_bar_9slice.png.import
Labels: art
